# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  actman_config = debug
endif
ifeq ($(config),release)
  actman_config = release
endif

PROJECTS := actman

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

actman:
ifneq (,$(actman_config))
	@echo "==== Building actman ($(actman_config)) ===="
	@${MAKE} --no-print-directory -C . -f actman.make config=$(actman_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f actman.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   actman"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"